apiVersion: apps/v1
kind: Deployment
metadata:
  name: newbackend-deployment
  labels:
    component: backend
    app: my-app

spec:
  template:
    metadata:
      name: newbackend-pod
      labels:
        component: backend
        app: my-app2
    spec:
      containers:
        - name: newbackend-container
          image: matmalecki/newbackend
  
  replicas: 3
  selector:
    matchLabels:
      app: my-app2
      component: backend